id: P96FAE8E4
initial_creation_type: input
source_metadata:
  title: Pema Karpo Series
  language: bo
  description: 'Texts by the Omniscient Pema Karpo (kun mkhyen padma dkar po) aka
    Ngawang Norbu (ngag dbang nor bu, 1527-1592), a great scholar and adept of the
    Drukpa Kagyü school:'
  volume:
    77d126e11f544dd3b63787c0e56e5d68:
      title: 'A Casket of Sacred Dharma: Stages of Meditation on Dependent Arising'
      parent: Commentaries
created_at: '2022-03-01T01:15:40.964447'
last_modified_at: '2022-03-01T01:15:40.964450'
statistics:
  total_words: 1910
  total_non_words: 210
quality:
  non_words_ratio: 0.11
